### ISSUE TITLE
`find_notebook_examples` utility for use in docs/make.jl?

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/JuliaGPsDocs.jl#14] opened 2022-04-07 14:07 UTC
@theogf given that JuliaGPsDocs is an opinionated package for making it easier to get consistent docs setup across our packages, how about we let it also provide this as a function so we can just do
```suggestion
        "Examples" => JuliaGPsDocs.find_notebook_examples(),
```
? :)

_Originally posted by @st-- in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/443#discussion_r845180559_

**Comment by theogf** [comment] 2022-04-07 14:29
Duplicate of #6

**Closed by theogf** 2022-04-07 14:29 UTC
